repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(tests/legacy|samples)/
      - id: check-yaml
        exclude: |
          (?x)^(
              meta.yaml
              | tests/legacy/
              | samples/
          )$
      - id: check-xml
        exclude: ^(tests/legacy|samples)/
      - id: check-json
        exclude: ^(tests/legacy|samples)/
      - id: detect-private-key
        exclude: ^(tests/legacy|samples)/
      - id: end-of-file-fixer
        exclude: ^(tests/legacy|samples)/
      - id: check-merge-conflict
        exclude: ^(tests/legacy|samples)/
      - id: check-added-large-files
        args: ['--maxkb=1024']
        exclude: ^(tests/legacy|samples)/
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

  # Google Java Format for Java code formatting
  - repo: local
    hooks:
      - id: google-java-format
        name: Google Java Format
        entry: bash lint.sh
        language: system
        files: \.java$
        pass_filenames: false
