// Auto-generated by tools/generate.py -- DO NOT EDIT.
package com.alibaba.dashscope.common;

import java.util.Map;

/** Internal error codes with two-layer message design. */
public enum InternalErrorCode {
  SDK_AGENTSTUDIO_NETWORK_ERROR(
      "sdk.agentstudio.NetworkError",
      PublicErrorCode.INTERNAL_ERROR,
      "Failed to establish or maintain connection with the server.",
      true,
      new String[] {},
      "Network connection failed",
      "Check network connection and retry"),
  SDK_AGENTSTUDIO_CONFLICT(
      "sdk.agentstudio.Conflict",
      PublicErrorCode.INVALID_REQUEST,
      "The request conflicts with the current state of the resource.",
      true,
      new String[] {},
      "Request conflicts with current resource state",
      "Retry later or check resource state"),
  SDK_AGENTSTUDIO_UNKNOWN_ERROR(
      "sdk.agentstudio.UnknownError",
      PublicErrorCode.INTERNAL_ERROR,
      "An unexpected error occurred.",
      false,
      new String[] {},
      "Unexpected error occurred",
      "Contact technical support");

  private final String code;
  private final PublicErrorCode external;
  private final String message;
  private final boolean allowRetry;
  private final String[] vars;
  private final String cause;
  private final String solution;

  InternalErrorCode(
      String code,
      PublicErrorCode external,
      String message,
      boolean allowRetry,
      String[] vars,
      String cause,
      String solution) {
    this.code = code;
    this.external = external;
    this.message = message;
    this.allowRetry = allowRetry;
    this.vars = vars;
    this.cause = cause;
    this.solution = solution;
  }

  public String getCode() {
    return code;
  }

  public PublicErrorCode getExternal() {
    return external;
  }

  public String getMessage() {
    return message;
  }

  public boolean isAllowRetry() {
    return allowRetry;
  }

  public String[] getVars() {
    return vars;
  }

  public String getCause() {
    return cause;
  }

  public String getSolution() {
    return solution;
  }

  public String formatMessage(Map<String, String> vars) {
    String msg = message;
    for (Map.Entry<String, String> entry : vars.entrySet()) {
      msg = msg.replace("{" + entry.getKey() + "}", entry.getValue());
    }
    return msg;
  }
}
