// Auto-generated by tools/generate.py -- DO NOT EDIT.
package com.alibaba.dashscope.common;

import java.util.Map;

/** Internal error codes with two-layer message design. */
public enum InternalErrorCode {
  SDK_AGENTSTUDIO_API_CONNECTION_ERROR(
      "sdk.agentstudio.APIConnectionError",
      PublicErrorCode.INTERNAL_ERROR,
      "Failed to connect to the AgentStudio service.",
      true,
      new String[] {},
      "",
      "Check your network connectivity and ensure the AgentStudio endpoint "
          + "(base_url / region) is reachable. Verify firewall and proxy settings."),
  SDK_AGENTSTUDIO_API_TIMEOUT_ERROR(
      "sdk.agentstudio.APITimeoutError",
      PublicErrorCode.REQUEST_TIMEOUT,
      "The request to the AgentStudio service timed out.",
      true,
      new String[] {},
      "",
      "The request did not complete within the timeout period. Increase the "
          + "client timeout or retry the request."),
  SDK_AGENTSTUDIO_STREAM_ERROR(
      "sdk.agentstudio.StreamError",
      PublicErrorCode.INTERNAL_ERROR,
      "The SSE stream encountered a fatal protocol error.",
      true,
      new String[] {},
      "",
      "Retry the streaming request. If the error persists, report it at "
          + "https://github.com/dashscope/dashscope-sdk-java/issues."),
  SDK_AGENTSTUDIO_STREAM_CLOSED_ERROR(
      "sdk.agentstudio.StreamClosedError",
      PublicErrorCode.INVALID_REQUEST,
      "Attempted I/O on an already-closed stream.",
      false,
      new String[] {},
      "",
      "Do not read from a stream after it has been closed. Consume the stream "
          + "before calling close().");

  private final String code;
  private final PublicErrorCode external;
  private final String message;
  private final boolean allowRetry;
  private final String[] vars;
  private final String cause;
  private final String solution;

  InternalErrorCode(
      String code,
      PublicErrorCode external,
      String message,
      boolean allowRetry,
      String[] vars,
      String cause,
      String solution) {
    this.code = code;
    this.external = external;
    this.message = message;
    this.allowRetry = allowRetry;
    this.vars = vars;
    this.cause = cause;
    this.solution = solution;
  }

  public String getCode() {
    return code;
  }

  public PublicErrorCode getExternal() {
    return external;
  }

  public String getMessage() {
    return message;
  }

  public boolean isAllowRetry() {
    return allowRetry;
  }

  public String[] getVars() {
    return vars;
  }

  public String getCause() {
    return cause;
  }

  public String getSolution() {
    return solution;
  }

  public String formatMessage(Map<String, String> vars) {
    String msg = message;
    for (Map.Entry<String, String> entry : vars.entrySet()) {
      msg = msg.replace("{" + entry.getKey() + "}", entry.getValue());
    }
    return msg;
  }
}
